stages:
  training:
    cmd: python ../../../src/Model_Training/Model_Training.py
    deps:
    - ../../../src/Model_Training/Model_Training.py
    - Reduced_Features.csv
    outs:
    - keras-model/
