stages:
  training:
    cmd:
    - pip install -r ../../../src/Model_Training/requirements.txt
    - python ../../../src/Model_Training/Model_Training.py

    # Publish confusion matrix diff
    - echo "# Multi Class Classification" >> report.md
    - echo "## Plots" >> report.md
    - git add \*.json
    - git add \*.csv
    params:
    - test_size
    - train.activation
    - train.batch_size
    - train.epochs
    - train.fc_layers
    deps:
    - ../../../src/Model_Training/Model_Training.py
    - Reduced_Features.csv
    outs:
    - keras_model.onnx
    # metrics:
    # - metrics.json:
    #     cache: false
    plots:
    - classes.csv:
        cache: false
        template: confusion
        x: actual
        y: predicted
