stages:
  requirements:
    cmd: pip install -r ../../../src/Model_Training/requirements.txt
  training:
    cmd: python ../../../src/Model_Training/Model_Training.py
    params:
    - train.epochs
    - train.batch_size
    - train.activation
    - train.fc_layers
    deps:
    - ../../../src/Model_Training/Model_Training.py
    - Reduced_Features.csv
    outs:
    - keras-model/
