stages:
  requirements:
    pip install -r ../../../src/Feature_Importance/requirements.txt
  feat-sel:
    cmd: python ../../../src/Feature_Importance/Feature_Importance.py
    params:
    - Feature_Selection.n_features
    deps:
    - ../../../src/Feature_Importance/Feature_Importance.py
    - Full_Features.csv
    outs:
    - ../2_Training_Workflow/Reduced_Features.csv
