name: run-feature-selection
on: [push]
jobs:
  run:
     runs-on: [ubuntu-latest]
     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
     steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-cml@v1
        - uses: iterative/setup-dvc@v1
        - uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Select Features
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          run:
            # Your ML workflow goes here
            pip install -r requirements.txt

            # Pull data and run cache from gstorage and reproduce pipeline
            dvc pull
            dvc repro

        - name: Write CML report
            run:
                # Publish confusion matrix diff
                echo "## Plots" >> ContinuousML/NQ_DR_4_10_20_Ideal_27/2_Training_Workflow/report.md
                echo "### Class confusions" >> ContinuousML/NQ_DR_4_10_20_Ideal_27/2_Training_Workflow/report.md
                dvc plots show ContinuousML/NQ_DR_4_10_20_Ideal_27/2_Training_Workflow/classes.csv --template confusion -x actual -y predicted --show-vega master > vega.json
                vl2png vega.json -s 1.5 | cml-publish --md >> ContinuousML/NQ_DR_4_10_20_Ideal_27/2_Training_Workflow/report.md

                cl-send-comment report.md
