name: run-feature-selection
on: [push]
jobs:
  run:
     runs-on: [ubuntu-latest]
     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
     steps:
        - uses: actions/checkout@v2
        - uses: google-github-actions/setup-gcloud@master
          with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCS_PROJECT }}
            export_default_credentials: true
        - name: Select Features
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Your ML workflow goes here
            pip install -r requirements.txt

            # Pull data and run cache from gstorage and reproduce pipeline
            dvc pull --run-cache
            dvc repro
