name: run-feature-selection
on: [push]
jobs:
  deploy-runner:
     runs-on: [ubuntu-latest]
     steps:
        - uses: actions/checkout@v2
        - uses: iterative/setup-cml@v1
        - uses: google-github-actions/setup-gcloud@master
          with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCS_PROJECT }}
            export_default_credentials: true
        - name: deploy
          shell: bash
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            cml-runner \
            --cloud aws \
            --cloud-region us-west \
            --cloud-type=g3.4xlarge \
            --cloud-hdd-size 64 \
            --labels=cml-runner

  run:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container:
      image: docker://iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Select Features
      env:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        dvc pull --run-cache
        dvc repro -R ContinuousML
        dvc push
        git add \*dvc.lock
        git commit -m "Github Actions Add Lock Files"
