name: run-feature-selection
on: [push]
jobs:
  run:
     runs-on: [ubuntu-latest]
     container: docker://ghcr.io/iterative/cml:0-dvc2-base1
     steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-cml@v1
        - uses: iterative/setup-dvc@v1
        - uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Select Features
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          run: |
            # Your ML workflow goes here
            pip install -r requirements.txt

            # Pull data and run cache from gstorage and reproduce pipeline
            dvc pull
            dvc repro
