name: run-feature-selection
on: [push]
jobs:
  deploy-runner:
     runs-on: [ubuntu-latest]
     steps:
        - uses: actions/checkout@v2
        - uses: iterative/setup-cml@v1
        - name: deploy
          shell: bash
          env:
            REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          run: |
            cml-runner \
            --cloud gcp \
            --cloud-region=europe-west4-b \
            --cloud-type=m \
            --cloud-gpu=tesla
            --labels=cml-runner

  run:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container:
      image: docker://iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Select Features
      env:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        dvc pull --run-cache
        dvc repro -R ContinuousML
        dvc push
        git add \*dvc.lock
        git commit -m "Github Actions Add Lock Files"
